/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuayRouteImport } from './routes/quay'
import { Route as LaySoRouteImport } from './routes/lay-so'
import { Route as IndexRouteImport } from './routes/index'

const QuayRoute = QuayRouteImport.update({
  id: '/quay',
  path: '/quay',
  getParentRoute: () => rootRouteImport,
} as any)
const LaySoRoute = LaySoRouteImport.update({
  id: '/lay-so',
  path: '/lay-so',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lay-so': typeof LaySoRoute
  '/quay': typeof QuayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lay-so': typeof LaySoRoute
  '/quay': typeof QuayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lay-so': typeof LaySoRoute
  '/quay': typeof QuayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lay-so' | '/quay'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lay-so' | '/quay'
  id: '__root__' | '/' | '/lay-so' | '/quay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LaySoRoute: typeof LaySoRoute
  QuayRoute: typeof QuayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quay': {
      id: '/quay'
      path: '/quay'
      fullPath: '/quay'
      preLoaderRoute: typeof QuayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lay-so': {
      id: '/lay-so'
      path: '/lay-so'
      fullPath: '/lay-so'
      preLoaderRoute: typeof LaySoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LaySoRoute: LaySoRoute,
  QuayRoute: QuayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
